### ISSUE TITLE
Can't build on vs2010(SP1) follow Building WebKit.NET with Visual Studio 2010 Express: A Visual Step By Step Guide

### ISSUE THREAD

**Issue by bygreencn** [webkitdotnet/webkitdotnet#26]
Step by step build the master branch with vs2010(sp1) according to the Building WebKit.NET with Visual Studio 2010 Express: A Visual Step By Step Guide, but still failed with the strong name signing of JSCore.dll. 
Anyone test it and how to do it?

**Comment by rawberg** [comment]
I get 77 build errors using Visual Studio Team Edition 2010. I also followed the steps in the "Step By Step Guide". I'm on a fresh install of VS2010 on an Win XP machine.

``` bash
Warning 1   warning MSB3245: Could not resolve this reference. Could not locate the assembly "WebKit.Interop, Version=534.0.0.0, Culture=neutral, PublicKeyToken=b967213f6d29a3be". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets  1360    10  JSCore
Error   2   error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   3   error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   4   error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Error   5   error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Warning 6   warning C4357: param array argument found in formal argument list for delegate 'JavaScriptFunction' ignored when generating 'WebKit::JSCore::JavaScriptFunction::BeginInvoke'   c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 17  1   JSCore
Error   7   error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   8   error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   9   error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   10  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   11  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   12  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   13  error C3699: '^' : cannot use this indirection on type 'IWebFrame'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   14  error C3083: 'Interop': the symbol to the left of a '::' must be a type C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  24  1   JSCore
Error   15  error C2039: 'IWebFrame' : is not a member of 'WebKit'  C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  24  1   JSCore
Error   16  error C3699: '^' : cannot use this indirection on type 'IWebFrame'  C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  24  1   JSCore
Error   17  error C3083: 'Interop': the symbol to the left of a '::' must be a type C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  27  1   JSCore
Error   18  error C3083: 'IWebFrame': the symbol to the left of a '::' must be a type   C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  27  1   JSCore
Error   19  error C3363: 'WebKit' : 'typeid' can only be applied to a type  C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  27  1   JSCore
Error   20  error C2665: 'System::Runtime::InteropServices::Marshal::GetComInterfaceForObject' : none of the 2 overloads could convert all the argument types   C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  27  1   JSCore
Error   21  error C2228: left of '.ToPointer' must have class/struct/union  C:\cygwin\home\Administrator\WebKitDotNet\JSCore\JSContext.cpp  27  1   JSCore
Error   22  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   23  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   24  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Error   25  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Warning 26  warning C4357: param array argument found in formal argument list for delegate 'JavaScriptFunction' ignored when generating 'WebKit::JSCore::JavaScriptFunction::BeginInvoke'   c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 17  1   JSCore
Error   27  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   28  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   29  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   30  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   31  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   32  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   33  error C3699: '^' : cannot use this indirection on type 'IWebFrame'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   34  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   35  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   36  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Error   37  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Warning 38  warning C4357: param array argument found in formal argument list for delegate 'JavaScriptFunction' ignored when generating 'WebKit::JSCore::JavaScriptFunction::BeginInvoke'   c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 17  1   JSCore
Error   39  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   40  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   41  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Error   42  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Warning 43  warning C4357: param array argument found in formal argument list for delegate 'JavaScriptFunction' ignored when generating 'WebKit::JSCore::JavaScriptFunction::BeginInvoke'   c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 17  1   JSCore
Error   44  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   45  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   46  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   47  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   48  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   49  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   50  error C3699: '^' : cannot use this indirection on type 'IWebFrame'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   51  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   52  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    5   1   JSCore
Error   53  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   54  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   55  error C3083: 'Interop': the symbol to the left of a '::' must be a type c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   56  error C2039: 'IWebFrame' : is not a member of 'WebKit'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   57  error C3699: '^' : cannot use this indirection on type 'IWebFrame'  c:\cygwin\home\administrator\webkitdotnet\jscore\JSContext.h    23  1   JSCore
Error   58  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   59  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSValue.h  5   1   JSCore
Error   60  error C2039: 'Interop' : is not a member of 'WebKit'    c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Error   61  error C2871: 'Interop' : a namespace with this name does not exist  c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 6   1   JSCore
Warning 62  warning C4357: param array argument found in formal argument list for delegate 'JavaScriptFunction' ignored when generating 'WebKit::JSCore::JavaScriptFunction::BeginInvoke'   c:\cygwin\home\administrator\webkitdotnet\jscore\JSObject.h 17  1   JSCore
Error   63  The type or namespace name 'IWebKitBrowserHost' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    42  55  WebKitBrowser
Error   64  The type or namespace name 'IWebKitBrowser' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    42  75  WebKitBrowser
Error   65  The type or namespace name 'WebKitBrowserCore' could not be found (are you missing a using directive or an assembly reference?) C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    44  26  WebKitBrowser
Error   66  The type or namespace name 'WebKitBrowserErrorEventHandler' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    111 22  WebKitBrowser
Error   67  The type or namespace name 'FileDownloadBeginEventHandler' could not be found (are you missing a using directive or an assembly reference?) C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    120 22  WebKitBrowser
Error   68  The type or namespace name 'NewWindowRequestEventHandler' could not be found (are you missing a using directive or an assembly reference?)  C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    129 22  WebKitBrowser
Error   69  The type or namespace name 'NewWindowCreatedEventHandler' could not be found (are you missing a using directive or an assembly reference?)  C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    138 22  WebKitBrowser
Error   70  The type or namespace name 'ShowJavaScriptAlertPanelEventHandler' could not be found (are you missing a using directive or an assembly reference?)  C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    147 22  WebKitBrowser
Error   71  The type or namespace name 'ShowJavaScriptConfirmPanelEventHandler' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    156 22  WebKitBrowser
Error   72  The type or namespace name 'ShowJavaScriptPromptPanelEventHandler' could not be found (are you missing a using directive or an assembly reference?) C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    165 22  WebKitBrowser
Error   73  The type or namespace name 'DOM' could not be found (are you missing a using directive or an assembly reference?)   C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    323 16  WebKitBrowser
Error   74  The type or namespace name 'CookieAcceptPolicy' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    436 16  WebKitBrowser
Error   75  The type or namespace name 'WebKitBrowserCore' could not be found (are you missing a using directive or an assembly reference?) C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    476 30  WebKitBrowser
Error   76  The type or namespace name 'IWebKitBrowserHost' could not be found (are you missing a using directive or an assembly reference?)    C:\cygwin\home\Administrator\WebKitDotNet\WebKitBrowser\WebKitBrowser.cs    624 9   WebKitBrowser
Error   77  Metadata file 'C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\WebKitCore.dll' could not be found WebKitBrowser.Tests
Error   78  Metadata file 'C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\WebKitBrowser.dll' could not be found  WebKitBrowser.Tests
Warning 79  Could not resolve this reference. Could not locate the assembly "WebKit.Interop". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   WebKitBrowser
Warning 80  Could not resolve this reference. Could not locate the assembly "WebKitCore". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   WebKitBrowser
Warning 81  The referenced component 'WebKit.Interop' could not be found.   
Warning 82  The referenced component 'WebKitCore' could not be found.   
Error   83  The referenced assembly "C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\JSCore.dll" was not found. If this assembly is produced by another one of your projects, please make sure to build that project before building this one.    WebKitBrowserTest
Error   84  The referenced assembly "C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\WebKitBrowser.dll" was not found. If this assembly is produced by another one of your projects, please make sure to build that project before building this one. WebKitBrowserTest
Error   85  The referenced assembly "C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\WebKitCore.dll" was not found. If this assembly is produced by another one of your projects, please make sure to build that project before building this one.    WebKitBrowserTest
Error   86  The referenced assembly "C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\JSCore.dll" was not found. If this assembly is produced by another one of your projects, please make sure to build that project before building this one.    WebKitCore
Error   87  The referenced assembly "C:\cygwin\home\Administrator\WebKitDotNet\bin\Release\JSCore.dll" was not found. If this assembly is produced by another one of your projects, please make sure to build that project before building this one.    JSCore.Tests
```

**Comment by peterdn** [comment]
Hey, try building again -- annoyingly it takes one build to generate the
required "WebKit.Interop.dll" and another before it actually finds that.

Peter

**Comment by rawberg** [comment]
Thanks for looking into this Peter! Unfortunately I didn't have any luck build/re-building the entire solution. However I did manage to make some progress by flipping it to release mode and individually building each project starting with JSCore, WebKitCore, then WebKitBrowser. 

However when I went to start an instance of WebKitBrowser I got the following error.
![Screen Shot 2013-03-25 at 9 42 56 AM](https://f.cloud.github.com/assets/19817/298949/fd668a2c-956b-11e2-92c2-e1473b0f0c89.png)

Followed by this exception.
![Screen Shot 2013-03-25 at 9 44 39 AM](https://f.cloud.github.com/assets/19817/298951/06cea356-956c-11e2-8442-aa75208c022d.png)

Any ideas? Also what versions of Windows and VS Studio do you use? Thanks!

**Comment by peterdn** [comment]
Interesting; I've not see that one before.  Looks like you're on XP -- I assume you're patched to at least SP2?  I'm using Windows 8 and Visual Studio 2010 at the moment.

Also, are you using the latest WebKit .NET on develop branch?  The WebKit.dll there was built using Visual Studio 2005, if I remember correctly, so you might be missing some VC++ 2005 libraries.  Try installing:

http://www.microsoft.com/en-gb/download/details.aspx?id=14431
http://www.microsoft.com/en-gb/download/details.aspx?id=26347
http://www.microsoft.com/en-gb/download/details.aspx?id=5638

**Comment by rawberg** [comment]
I installed the VC++ 2005 Service Pack and it didn't seem to help. I'm running WinXP SP3 (32bit) on a Virtual Machine that I purpose built for compiling this project and Webkit (Wincairo). I have VS Studio 2005, 2008 and 2010 installed.

Maybe I should setup a VM that has your exact environment. Will VS Studio 2005 run on Windows 8? What edition of Windows 8 are you using? What versions of VS Studio do you have installed, just 2005 and 2010?

**Comment by peterdn** [comment]
Yup, I have all VS 2005 through 2012 installed on Windows 8 Pro. With that setup it should work fine on any versions of Windows 7 or 8. It's possible that there's something going on that just won't work with XP -- I'm struggling to get it to even run the non-.NET WebKit launcher app.

**Comment by rawberg** [comment]
Ok I'll rebuild my VM with Win 8 Pro and VS 2005 - 2012 and that should bring us into dev environment parity. I'll update this thread once I try building again in Win 8. Do you use any specific versions of VS Studio like express, team, pro, etc..? I have BizSpark so I can install whatever version.

**Comment by peterdn** [comment]
I have VS 2010 Ultimate, the rest Professional. VS2005 SP1 is installed.

**Comment by rawberg** [comment]
After a long night of corralling all the Visual Studio versions into place on Windows 8 I'm happy to say it builds! Only issue now is actually running it. It looks like VS can't find the dlls WebKitBrowser.dll depends on. I can see them all in the bin folder of the project root. How do I get VS to automatically copy or reference them?

``` bash
System.BadImageFormatException was unhandled
  HResult=-2147024885
  Message=Could not load file or assembly 'file:///C:\cygwin\home\David\WebKitDotNet\WebKitBrowser\obj\Debug\WebKitBrowser.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Source=mscorlib
  FileName=file:///C:\cygwin\home\David\WebKitDotNet\WebKitBrowser\obj\Debug\WebKitBrowser.dll
  FusionLog==== Pre-bind state information ===
LOG: User = WIN-QQADBKLQHE7\David
LOG: Where-ref bind. Location = C:\cygwin\home\David\WebKitDotNet\WebKitBrowser\obj\Debug\WebKitBrowser.dll
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Attempting download of new URL file:///C:/cygwin/home/David/WebKitDotNet/WebKitBrowser/obj/Debug/WebKitBrowser.dll.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

  StackTrace:
       at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
       at System.Reflection.Assembly.LoadFrom(String assemblyFile)
       at Microsoft.VisualStudio.Tools.UserControlTestContainer.LoadAssemblyFromFile(String fileName)
       at Microsoft.VisualStudio.Tools.UserControlTestContainer.UserControlTestContainer_Load(Object sender, EventArgs e)
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException: 

```

**Comment by peterdn** [comment]
So you get this error when running WebKitBrowserTest.exe?  Are you using the WebKit build from WebKit .NET or your own build?

**Comment by rawberg** [comment]
I get the error when trying to run it in debug mode inside VS.

**Comment by peterdn** [comment]
Double check that it's building everything x86 only.  Otherwise it looks like you may still be missing some VC++ dependencies that WebKit needs.

Add me on Skype ({redacted}) or Google Chat if you want to sort this out over IM.  Might be easier in real-time.

**Comment by peterdn** [comment]
Ah, actually, it could be because you're trying to run the WebKitBrowser project.  Set WebKitBrowserTest as the startup project instead.

**Comment by rawberg** [comment]
That did it! Got it working! Thank you!
